import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Problem from "@/components/Problem";
import Benefits from "@/components/Benefits";
import Process from "@/components/Process";
import FAQ from "@/components/FAQ";
import Urgency from "@/components/Urgency";
import FlodeskForm from "@/components/FlodeskForm";
import MobileBookingCTA from "@/components/MobileBookingCTA";

export default function Home() { return <><a className="skip-link" href="#main-content">Skip to content</a><main id="main-content"><Header /><Hero /><Problem /><Benefits /><Process /><FAQ /><Urgency /><section id="consultation-form" className="scroll-mt-4 bg-mist px-4 py-14 sm:px-5 sm:py-28"><div className="consultation-panel mx-auto grid max-w-6xl gap-7 rounded-[1.5rem] p-4 shadow-soft ring-1 ring-blue-500/40 sm:gap-10 sm:rounded-[2rem] sm:p-10 lg:grid-cols-[.8fr_1.2fr] lg:gap-14 lg:p-14"><div className="order-2 flex flex-col lg:order-1"><span className="eyebrow w-fit">Free consultation</span><h2 className="mt-5 text-3xl font-extrabold tracking-tight text-white sm:text-4xl">Let&apos;s find your smartest next move.</h2><p className="mt-5 leading-7 text-lilac">Share a few details about your business. Your consultation will focus on practical ways to create more consistent customer enquiries online.</p><div className="mt-9 space-y-4 border-t border-white/10 pt-8"><p className="consultation-check">One-to-one consultation, focused on your business</p><p className="consultation-check">A customized AI-powered marketing strategy</p><p className="consultation-check">A simple action plan you can understand and use</p></div><p className="mt-auto pt-8 text-sm leading-6 text-blue-100">Your details are handled through our secure Flodesk form. No spam.</p></div><div className="order-1 rounded-2xl border border-white/10 bg-ink/35 p-4 sm:p-7 lg:order-2"><div className="mb-6 flex items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.15em] text-blue-200">Request your free consultation</p><p className="mt-2 text-sm leading-5 text-lilac">Takes less than 2 minutes to complete.</p></div><span className="shrink-0 rounded-full border border-blue-400/30 bg-blue/10 px-3 py-1 text-xs font-bold text-blue-100">Free</span></div><FlodeskForm /></div></div></section></main><MobileBookingCTA /></>; }
