import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Problem from "@/components/Problem";
import Benefits from "@/components/Benefits";
import Process from "@/components/Process";
import FAQ from "@/components/FAQ";
import Urgency from "@/components/Urgency";
import FlodeskForm from "@/components/FlodeskForm";

export default function Home() { return <><a className="skip-link" href="#main-content">Skip to content</a><main id="main-content"><Header /><Hero /><Problem /><Benefits /><Process /><FAQ /><Urgency /><section id="consultation-form" className="bg-mist px-5 py-20 sm:py-28"><div className="consultation-panel mx-auto grid max-w-6xl gap-10 rounded-[2rem] p-6 shadow-soft ring-1 ring-blue-500/40 sm:p-10 lg:grid-cols-[.8fr_1.2fr] lg:gap-14 lg:p-14"><div className="flex flex-col"><span className="eyebrow w-fit">Free consultation</span><h2 className="mt-5 text-3xl font-extrabold tracking-tight text-white sm:text-4xl">Let&apos;s find your smartest next move.</h2><p className="mt-5 leading-7 text-lilac">Share a few details about your business. Your consultation will focus on practical ways to create more consistent customer enquiries online.</p><div className="mt-9 space-y-4 border-t border-white/10 pt-8"><p className="consultation-check">One-to-one consultation, focused on your business</p><p className="consultation-check">A customized AI-powered marketing strategy</p><p className="consultation-check">A simple action plan you can understand and use</p></div><p className="mt-auto pt-8 text-sm leading-6 text-blue-100">Your details are handled through our secure Flodesk form. No spam.</p></div><div className="rounded-2xl border border-white/10 bg-ink/35 p-5 sm:p-7"><p className="mb-6 text-sm font-bold uppercase tracking-[.15em] text-blue-200">Request your free consultation</p><FlodeskForm /></div></div></section></main><a href="#consultation-form" className="fixed bottom-4 left-4 right-4 z-20 flex min-h-14 items-center justify-center rounded-full bg-blue px-6 font-bold text-white shadow-lg shadow-blue-950/50 transition hover:bg-blue-700 sm:hidden">Book Free Consultation <span className="ml-2">→</span></a></>; }
