"use client";

import { useEffect, useState } from "react";
import Header from "@/components/Header";

export default function ThankYou() {
  const [name, setName] = useState("");
  useEffect(() => { setName(sessionStorage.getItem("consultationName") || ""); }, []);

  return <main className="min-h-screen bg-ink"><Header /><section className="hero-grid px-5 pb-20 pt-16 text-center sm:pt-24"><div className="mx-auto max-w-3xl rounded-3xl border border-blue-500/40 bg-plum p-8 shadow-soft sm:p-14"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-blue text-2xl font-bold text-white" aria-hidden>✓</div><p className="mt-7 text-sm font-bold uppercase tracking-[.16em] text-blue-300">Request received</p><h1 className="mt-4 text-4xl font-extrabold tracking-tight text-white sm:text-5xl">{name ? `Thanks, ${name}!` : "Your Free Consultation Has Been Booked!"}</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-lilac">You&apos;re one step closer to getting a customized AI-powered marketing plan for your business.</p><p className="mx-auto mt-4 max-w-xl leading-7 text-blue-100">Watch this short video before we speak to get the most value from your consultation.</p><div className="mx-auto mt-9 max-w-sm overflow-hidden rounded-2xl border border-blue-500/40 bg-ink/70 shadow-xl shadow-black/30"><video className="aspect-[9/16] w-full bg-black" controls playsInline preload="metadata"><source src="/thank-you-video.mp4" type="video/mp4" />Your browser does not support this video.</video></div><div className="mt-9 rounded-2xl border border-green-400/30 bg-green-950/20 p-6"><h2 className="text-xl font-bold text-white">Have a question before the call?</h2><p className="mt-2 leading-7 text-lilac">Send a quick WhatsApp message and introduce your business.</p><a href="https://wa.me/9779861676300?text=Hi%20Parmeshwor%2C%20I%20just%20booked%20a%20free%20consultation." target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-12 items-center justify-center rounded-full bg-[#25D366] px-6 font-bold text-white shadow-lg shadow-green-950/40 transition hover:-translate-y-0.5 hover:bg-[#1EBE5D]">Chat on WhatsApp <span aria-hidden className="ml-2">↗</span></a></div><div className="mt-9 rounded-2xl border border-white/10 bg-ink/60 p-6 text-left"><h2 className="text-xl font-bold text-white">Here&apos;s what happens next</h2><ul className="mt-4 space-y-3 leading-7 text-lilac"><li>✓ Watch the video above.</li><li>✓ We&apos;ll review your business details before the consultation.</li><li>✓ We&apos;ll contact you by email or WhatsApp to arrange a suitable time.</li><li>✓ During the call, you&apos;ll receive a customized marketing strategy built specifically for your business.</li></ul></div><p className="mt-8 leading-7 text-lilac">I look forward to speaking with you and helping you attract more customers online.</p><a href="/" className="mt-8 inline-flex rounded-full border border-blue-500/50 px-6 py-3.5 font-bold text-white transition hover:bg-blue-500/10">Back to home</a></div></section></main>;
}
